-- Todos os dados
SELECT * FROM [TABELA DE CLIENTES]
SELECT * FROM [TABELA DE PRODUTOS]
SELECT * FROM [TABELA DE VENDEDORES]

-- Selecionar colunas específicas
SELECT [NOME], [ESTADO] FROM [TABELA DE CLIENTES]
SELECT [NOME DO PRODUTO], [PRECO DE LISTA] FROM [TABELA DE PRODUTOS]
SELECT * FROM [TABELA DE VENDEDORES]
SELECT [NOME] FROM [TABELA DE VENDEDORES]
