CREATE TABLE [TABELA DE VENDEDORES] (
    [MATRICULA] [VARCHAR] (5) NOT NULL PRIMARY KEY,
    [NOME] [VARCHAR] (150) NOT NULL,
    [PERCENTUAL COMISSAO] [DECIMAL] (5,2) NOT NULL 
);

INSERT INTO [TABELA DE VENDEDORES] VALUES
('00236','Cláudia Morais',0.08),
('00237','Marcela Ferreira',0.09),
('00238','Márcio Almeida',0.08);

SELECT * FROM [TABELA DE VENDEDORES];
