-- Agrupa por tipo de embalagem, e soma todos os valores (SUM)
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

-- Agrupa por tipo de embalagem e pega o valor minimo que tiver (MIN)
SELECT EMBALAGEM, MIN(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

-- Agrupa por cidade, a média de idade e a soma de limite de crédito
SELECT CIDADE, AVG(IDADE) AS MEDIA_IDADE, SUM(LIMITE_DE_CREDITO) AS CREDITO_LIMITE FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

-- Contar linhas || QTD de clientes por cidade
SELECT CIDADE, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

-- Numero de embalagem de produtos de laranja
SELECT EMBALAGEM, COUNT (*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'laranja'
GROUP BY EMBALAGEM;


-- DESAFIO
SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = '1101035' 
AND QUANTIDADE = 99;
