-- CASE WHEN <condição> THEN <valor>
-- CASE WHEN <condição> THEN <valor>
-- CASE WHEN <condição> THEN <valor>
-- ELSE <valor> END


SELECT NOME, IDADE, 
CASE
    WHEN IDADE > 20 THEN 'MAIOR DE 20' 
    ELSE 'MENOR DE 20'
END AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES;  

--
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE    
    WHEN PRECO_DE_LISTA > 12 THEN 'CARO'
    WHEN PRECO_DE_LISTA BETWEEN 5 AND 11 THEN 'EM CONTA'
ELSE 'BARATO'
END AS VALORES
FROM TABELA_DE_PRODUTOS
ORDER BY VALORES;

--
SELECT 
CASE    
    WHEN PRECO_DE_LISTA > 12 THEN 'CARO'
    WHEN PRECO_DE_LISTA BETWEEN 5 AND 11 THEN 'EM CONTA'
ELSE 'BARATO'
END AS VALORES, COUNT(*) AS NUMERO_DE_PRODUTOS
FROM TABELA_DE_PRODUTOS
GROUP BY CASE    
    WHEN PRECO_DE_LISTA > 12 THEN 'CARO'
    WHEN PRECO_DE_LISTA BETWEEN 5 AND 11 THEN 'EM CONTA'
    ELSE 'BARATO'
END;

-- Desafio
SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'Clientes medios'
ELSE 'Clientes pequenos' END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES;