SELECT NOME, IDADE FROM TABELA_DE_CLIENTES 
WHERE IDADE > 18;

SELECT NOME, IDADE FROM TABELA_DE_CLIENTES 
WHERE IDADE = 18;

SELECT NOME, IDADE FROM TABELA_DE_CLIENTES 
WHERE IDADE < 18;

-- Diferente
SELECT NOME, IDADE FROM TABELA_DE_CLIENTES 
WHERE IDADE <> 18;

-- Entre
SELECT NOME, IDADE FROM TABELA_DE_CLIENTES 
WHERE IDADE BETWEEN 18 AND 25;

-- Data: YYY-MM-DD
SELECT NOME, DATA_DE_NASCIMENTO FROM TABELA_DE_CLIENTES
WHERE DATA_DE_NASCIMENTO > '1995-11-14';

-- Ordem alfabética
SELECT NOME, BAIRRO FROM TABELA_DE_CLIENTES
WHERE BAIRRO >= 'lapa';

SELECT NOME, BAIRRO FROM TABELA_DE_CLIENTES
WHERE BAIRRO <> 'tijuca';