-- Consultar campos específicos
SELECT NOME, CPF, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

-- Apelidando colunas (alias)
SELECT CPF AS [ID CLIENTE], NOME AS [NOME CLIENTE] FROM TABELA_DE_CLIENTES TC;

SELECT TC.NOME, TC.CIDADE, TC.BAIRRO, TC.ESTADO FROM TABELA_DE_CLIENTES TC;
SELECT TABELA_DE_CLIENTES.NOME, TABELA_DE_CLIENTES.BAIRRO, TABELA_DE_CLIENTES.ESTADO FROM TABELA_DE_CLIENTES;